
import java.awt.Dimension;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class admin_insert extends javax.swing.JFrame {

    /**
     * Creates new form admin_insert
     */
    public admin_insert() {
        initComponents();
        setMinimumSize(new Dimension(480,380).getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t7 = new java.awt.TextField();
        t8 = new java.awt.TextField();
        t9 = new java.awt.TextField();
        b1 = new java.awt.Button();
        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label10.setText("pharmacy name");
        getContentPane().add(label10);
        label10.setBounds(50, 44, 93, 20);

        label11.setText("location");
        getContentPane().add(label11);
        label11.setBounds(50, 74, 47, 20);

        label12.setText("sector");
        getContentPane().add(label12);
        label12.setBounds(50, 104, 38, 20);

        label13.setText("city");
        getContentPane().add(label13);
        label13.setBounds(50, 134, 21, 20);

        label14.setText("contact");
        getContentPane().add(label14);
        label14.setBounds(50, 164, 43, 20);

        label15.setText("email address");
        getContentPane().add(label15);
        label15.setBounds(50, 194, 84, 20);

        label16.setText("opening time");
        getContentPane().add(label16);
        label16.setBounds(50, 224, 76, 20);

        label17.setText("closing time");
        getContentPane().add(label17);
        label17.setBounds(50, 254, 71, 20);

        label18.setText("website (if any)");
        getContentPane().add(label18);
        label18.setBounds(50, 284, 86, 20);
        getContentPane().add(t1);
        t1.setBounds(255, 44, 100, 20);
        getContentPane().add(t2);
        t2.setBounds(255, 74, 100, 20);
        getContentPane().add(t3);
        t3.setBounds(255, 104, 100, 20);
        getContentPane().add(t4);
        t4.setBounds(255, 134, 100, 20);
        getContentPane().add(t5);
        t5.setBounds(255, 164, 100, 20);
        getContentPane().add(t6);
        t6.setBounds(255, 194, 100, 20);
        getContentPane().add(t7);
        t7.setBounds(255, 224, 100, 20);
        getContentPane().add(t8);
        t8.setBounds(255, 254, 100, 20);
        getContentPane().add(t9);
        t9.setBounds(255, 284, 100, 20);

        b1.setLabel("INSERT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(179, 314, 60, 24);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Enter Details");
        getContentPane().add(label1);
        label1.setBounds(170, 0, 94, 23);

        button1.setLabel("back");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(0, 0, 32, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wert.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 480, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String p,l,s,c,co,e,o,cl,w;
            if(t1.getText().length()==0||t2.getText().length()==0||t3.getText().length()==0||t4.getText().length()==0
                    ||t5.getText().length()==0||t6.getText().length()==0 ||t7.getText().length()==0||t8.getText().length()==0||t9.getText().length()==0)
            {
                JOptionPane.showMessageDialog(this,"Please fill the values");
                return;
            }
            p=t1.getText();
            l=t2.getText();
            s=t3.getText();
            c=t4.getText();
            co=t5.getText();
            e=t6.getText();
            o=t7.getText();
            cl=t8.getText();
            w=t9.getText();
           
            if(co.length()!=10)
            {
                JOptionPane.showMessageDialog(this,"contact can be of 10 digits only");
                return;
            }
           
            String q="insert into tbchemist(pharmacy,location,sector,city,contact,email,opening_time,closing_time,website) values(?,?,?,?,?,?,?,?,?)";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,p);
            pst.setString(2,l);
            pst.setString(3,s);
            pst.setString(4,c);
            pst.setString(5,co);
            pst.setString(6,e);
            pst.setString(7,o);
            pst.setString(8,cl);
            pst.setString(9,w);
            pst.executeUpdate();
            
           }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
                                     
    }//GEN-LAST:event_b1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private java.awt.TextField t9;
    // End of variables declaration//GEN-END:variables
}
