
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class chemist_med extends javax.swing.JFrame {

    /**
     * Creates new form chemist_med
     */
    public chemist_med() {
        initComponents();
        setMinimumSize(new Dimension(480,380).getSize());
        getdata();
    }

    void getdata()
    {
        try
        {
          String q="select disease from tbcategory";
          myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            ResultSet rs;
            rs=pst.executeQuery();
            while(rs.next())
                    {
                       c1.add(""+rs.getString("disease")); 
                    }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        c1 = new java.awt.Choice();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        ch1 = new java.awt.Checkbox();
        label4 = new java.awt.Label();
        t2 = new java.awt.TextField();
        t1 = new java.awt.TextField();
        label5 = new java.awt.Label();
        t3 = new java.awt.TextField();
        b1 = new java.awt.Button();
        label6 = new java.awt.Label();
        t4 = new java.awt.TextField();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setText("Select category");
        getContentPane().add(label1);
        label1.setBounds(54, 64, 87, 20);
        getContentPane().add(c1);
        c1.setBounds(267, 64, 100, 20);

        label2.setText("Medicine name");
        getContentPane().add(label2);
        label2.setBounds(54, 108, 88, 20);

        label3.setText("price");
        getContentPane().add(label3);
        label3.setBounds(54, 154, 31, 20);

        ch1.setLabel("Available");
        ch1.setName(""); // NOI18N
        getContentPane().add(ch1);
        ch1.setBounds(267, 194, 75, 20);

        label4.setText("status");
        getContentPane().add(label4);
        label4.setBounds(54, 194, 38, 20);
        getContentPane().add(t2);
        t2.setBounds(267, 154, 100, 20);
        getContentPane().add(t1);
        t1.setBounds(267, 108, 100, 20);

        label5.setText("Quantity");
        getContentPane().add(label5);
        label5.setBounds(54, 233, 48, 20);
        getContentPane().add(t3);
        t3.setBounds(267, 233, 92, 20);

        b1.setLabel("INSERT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(156, 263, 60, 24);

        label6.setText("Pharmacy name");
        getContentPane().add(label6);
        label6.setBounds(54, 34, 94, 20);
        getContentPane().add(t4);
        t4.setBounds(267, 34, 100, 20);

        button1.setLabel("back");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(0, 0, 39, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wert.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 410, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String q="select * from tbcategory where disease=?";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,c1.getSelectedItem());
            ResultSet rs;
            rs=pst.executeQuery();
            rs.next();
            int id=rs.getInt("c_id");
            String q1="insert into tbmedicine(medicine_name,c_id,price,pname,status,quantity) values(?,?,?,?,?,?)";
            String mname=t1.getText();
            double price=Double.parseDouble(t2.getText());
            int quan=Integer.parseInt(t3.getText());
            boolean status=ch1.getState();
            String pname=t4.getText();
            myconnection obj1=new myconnection();
            PreparedStatement pst1=obj1.db.prepareStatement(q1);
            pst1.setString(1,mname);
            pst1.setInt(2,id);
            pst1.setDouble(3,price);
            pst1.setString(4,pname);
            pst1.setBoolean(5,status);
            pst1.setInt(6,quan);
            pst1.executeUpdate();
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        new chempriv().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chemist_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chemist_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chemist_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chemist_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chemist_med().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button button1;
    private java.awt.Choice c1;
    private java.awt.Checkbox ch1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    // End of variables declaration//GEN-END:variables
}
