
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class chemistform extends javax.swing.JFrame {

    /**
     * Creates new form chemistform
     */
    public chemistform() {
        initComponents();
        setMinimumSize(new Dimension(480,380).getSize());
        
    }
  void getdata()
  {
      try
      {
          
      }
      catch(Exception e)
      {
          System.out.println(e.getMessage());
      }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        b1 = new java.awt.Button();
        b3 = new java.awt.Button();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t7 = new java.awt.TextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        t8 = new java.awt.TextField();
        t9 = new java.awt.TextField();
        label10 = new java.awt.Label();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setText("pharmacy name");
        getContentPane().add(label1);
        label1.setBounds(49, 34, 93, 20);

        label2.setText("location");
        getContentPane().add(label2);
        label2.setBounds(95, 64, 47, 20);

        label3.setText("contact");
        getContentPane().add(label3);
        label3.setBounds(95, 154, 43, 20);

        label4.setText("email address");
        getContentPane().add(label4);
        label4.setBounds(58, 184, 84, 20);

        label5.setText("opening time");
        getContentPane().add(label5);
        label5.setBounds(66, 214, 76, 20);

        label6.setText("closing time");
        getContentPane().add(label6);
        label6.setBounds(71, 242, 71, 20);

        label7.setText("website (if any)");
        getContentPane().add(label7);
        label7.setBounds(56, 272, 86, 20);

        b1.setLabel("insert medical info");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(130, 332, 117, 24);

        b3.setLabel("update personal info");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(348, 332, 129, 24);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(227, 34, 100, 20);
        getContentPane().add(t2);
        t2.setBounds(227, 64, 100, 20);
        getContentPane().add(t3);
        t3.setBounds(227, 154, 100, 20);
        getContentPane().add(t4);
        t4.setBounds(227, 184, 100, 20);
        getContentPane().add(t5);
        t5.setBounds(227, 214, 100, 20);
        getContentPane().add(t6);
        t6.setBounds(227, 244, 100, 20);
        getContentPane().add(t7);
        t7.setBounds(227, 274, 100, 20);

        label8.setText("sector");
        getContentPane().add(label8);
        label8.setBounds(95, 94, 38, 20);

        label9.setText("city");
        getContentPane().add(label9);
        label9.setBounds(95, 124, 21, 20);
        getContentPane().add(t8);
        t8.setBounds(227, 94, 100, 20);
        getContentPane().add(t9);
        t9.setBounds(227, 124, 100, 20);

        label10.setText("(enter pharmacy name to update details)");
        getContentPane().add(label10);
        label10.setBounds(348, 34, 226, 20);

        button1.setLabel("back");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(0, 0, 43, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wert.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 610, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
            // TODO add your handling code here:
            try
        {
            String p,l,s,c,co,e,o,cl,w;
            String q="update tbchemist set location=?,sector=?,city=?,contact=?,email=?,opening_time=?,closing_time=?,website=? where pharmacy=?";
            p=t1.getText();
            l=t2.getText();
            s=t8.getText();
            c=t9.getText();
            co=t3.getText();
            e=t4.getText();
            o=t5.getText();
            cl=t6.getText();
            w=t7.getText();
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,l);
            pst.setString(2,s);
            pst.setString(3,c);
            pst.setString(4,co);
            pst.setString(5,e);
            pst.setString(6,o);
            pst.setString(7,cl);
            pst.setString(8,w);
            pst.setString(9,p);
            pst.executeUpdate();
            
           }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String p;
            p=t1.getText();
            String q="select * from tbchemist where pharmacy=?";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,p);
            ResultSet rs;
            rs=pst.executeQuery();
            rs.next();
            t2.setText(rs.getString("location"));
            t8.setText(rs.getString("sector"));
            t9.setText(rs.getString("city"));
            t3.setText(rs.getString("contact"));
            t4.setText(rs.getString("email"));
            t5.setText(rs.getString("opening_time"));
            t6.setText(rs.getString("closing_time"));
            t7.setText(rs.getString("website"));
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_t1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        chemist_med c=new chemist_med();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
         new chempriv().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chemistform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chemistform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chemistform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chemistform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chemistform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button b3;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private java.awt.TextField t9;
    // End of variables declaration//GEN-END:variables
}
