
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setMinimumSize(new Dimension(480,380).getSize());
        c1.add("Admin");
        c1.add("Pharmicist");
        c1.add("User");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        b1 = new java.awt.Button();
        c1 = new java.awt.Choice();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(153, 255, 153));
        label1.setText("login as");
        getContentPane().add(label1);
        label1.setBounds(56, 40, 61, 20);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(153, 255, 153));
        label2.setText("username");
        getContentPane().add(label2);
        label2.setBounds(56, 80, 61, 20);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(153, 255, 153));
        label3.setText("password");
        getContentPane().add(label3);
        label3.setBounds(56, 121, 60, 20);

        b1.setBackground(new java.awt.Color(153, 255, 153));
        b1.setLabel("LOGIN");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(152, 186, 53, 24);
        getContentPane().add(c1);
        c1.setBounds(208, 40, 100, 20);
        getContentPane().add(t1);
        t1.setBounds(208, 80, 100, 20);
        getContentPane().add(t2);
        t2.setBounds(208, 121, 100, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tyui.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try
        {
            
            String l,u,p;
            l=c1.getSelectedItem();
            u=t1.getText();
            t2.setEchoChar('*');
            p=t2.getText();
            
            if(l.equals("User"))
            {
            String q="select username and password from tbsignup where username=? and password=?";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,u);
            pst.setString(2,p);
            ResultSet rs;
            rs=pst.executeQuery();
               if(rs.next())
               {
                  mainpage m=new mainpage(u);
                   m.setVisible(true);
                   this.setVisible(false); 
               }  
                
            }
            if(l.equals("Pharmacist"))
            {
            String q="select username and password from tbpharmacist where username=? and password=?";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,u);
            pst.setString(2,p);
            ResultSet rs;
            rs=pst.executeQuery();
               if(rs.next())
                {
                    //System.out.println("helllloooo");
                       chempriv c=new chempriv();
                       c.setVisible(true);
                       this.setVisible(false);
                }   
                
            }
            if(l.equals("Admin"))
            {
            String q="select username and password from tbadmin where username=? and password=?";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,u);
            pst.setString(2,p);
            ResultSet rs;
            rs=pst.executeQuery();
               if(rs.next())
                {
                    admin a=new admin();
                    a.setVisible(true);
                    this.setVisible(false);
                }
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Choice c1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    // End of variables declaration//GEN-END:variables
}
