
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell 
 */
public class mainpage extends javax.swing.JFrame {

    /**
     * Creates new form mainpage
     */
    public mainpage(String u) {
        initComponents();
        setMinimumSize(new Dimension(600,400).getSize());
        t2.setText(u);
        getdata();
    }

    void getdata()
    {
        try
        {
        String q="select * from tbcategory";
        myconnection obj=new myconnection();
        PreparedStatement pst=obj.db.prepareStatement(q);
        ResultSet rs;
        rs=pst.executeQuery();
        while(rs.next())
        {
            c1.add(rs.getString("disease"));
        }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        c1 = new java.awt.Choice();
        c2 = new java.awt.Choice();
        t1 = new java.awt.TextField();
        button2 = new java.awt.Button();
        l1 = new java.awt.Label();
        l3 = new java.awt.Label();
        l5 = new java.awt.Label();
        l7 = new java.awt.Label();
        l9 = new java.awt.Label();
        l4 = new java.awt.Label();
        l2 = new java.awt.Label();
        l6 = new java.awt.Label();
        l8 = new java.awt.Label();
        l10 = new java.awt.Label();
        label4 = new java.awt.Label();
        t2 = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        button1.setLabel("GET DETAILS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setText("select category");
        getContentPane().add(label1);
        label1.setBounds(70, 90, 86, 20);

        label2.setText("select medicine");
        getContentPane().add(label2);
        label2.setBounds(70, 120, 91, 20);

        label3.setText("Quantity");
        getContentPane().add(label3);
        label3.setBounds(80, 150, 48, 20);

        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(380, 90, 100, 20);
        getContentPane().add(c2);
        c2.setBounds(380, 120, 100, 20);
        getContentPane().add(t1);
        t1.setBounds(380, 150, 100, 20);

        button2.setLabel("GET DETAILS");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(240, 180, 92, 24);

        l1.setText("label4");
        getContentPane().add(l1);
        l1.setBounds(60, 240, 300, 20);

        l3.setText("label5");
        getContentPane().add(l3);
        l3.setBounds(60, 270, 300, 20);

        l5.setText("label6");
        getContentPane().add(l5);
        l5.setBounds(60, 300, 300, 20);

        l7.setText("label7");
        getContentPane().add(l7);
        l7.setBounds(60, 330, 300, 20);

        l9.setText("label8");
        getContentPane().add(l9);
        l9.setBounds(60, 360, 300, 20);

        l4.setText("label9");
        getContentPane().add(l4);
        l4.setBounds(390, 270, 99, 20);

        l2.setText("label10");
        getContentPane().add(l2);
        l2.setBounds(390, 240, 99, 20);

        l6.setText("label11");
        getContentPane().add(l6);
        l6.setBounds(390, 300, 99, 20);

        l8.setText("label12");
        getContentPane().add(l8);
        l8.setBounds(390, 330, 99, 20);

        l10.setText("label13");
        getContentPane().add(l10);
        l10.setBounds(390, 360, 99, 20);

        label4.setText("username");
        getContentPane().add(label4);
        label4.setBounds(70, 60, 100, 20);
        getContentPane().add(t2);
        t2.setBounds(380, 60, 100, 20);

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Chemist");
        getContentPane().add(label5);
        label5.setBounds(70, 210, 51, 20);

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText("Contact Number");
        getContentPane().add(label6);
        label6.setBounds(390, 210, 96, 20);

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("Enter Details");
        getContentPane().add(label7);
        label7.setBounds(220, 40, 116, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wert.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 590, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        // TODO add your handling code here:
        try
        {
            String prev;
            c2.removeAll();
           String q1="select * from tbcategory where disease=?";
            myconnection obj1=new myconnection();
            PreparedStatement pst1=obj1.db.prepareStatement(q1);
            pst1.setString(1,c1.getSelectedItem());
            ResultSet rs1;
            rs1=pst1.executeQuery();
            rs1.next();
            int id=rs1.getInt("c_id");
          String q="select * from tbmedicine where c_id=?";
        myconnection obj=new myconnection();
        PreparedStatement pst=obj.db.prepareStatement(q);
        pst.setInt(1,id);
        ResultSet rs;
        rs=pst.executeQuery();
        rs.next();
         prev=rs.getString("medicine_name");
        while(rs.next())
        { 
            if(!prev.equals(rs.getString("medicine_name")))
            {c2.add(rs.getString("medicine_name"));
            prev=rs.getString("medicine_name");
            }
        }
        
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_c1ItemStateChanged

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String category,medicine,quant;
            category=c1.getSelectedItem();
            medicine=c2.getSelectedItem();
            quant=t1.getText();
            String q="select * from tbcategory where disease=?";
            myconnection obj=new myconnection();
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,category);
            ResultSet rs1;
            rs1=pst.executeQuery();
            rs1.next();
            int id=rs1.getInt("c_id");
            String q1="select * from tbmedicine where c_id=? and medicine_name=?";
            myconnection obj1=new myconnection();
            PreparedStatement pst1=obj1.db.prepareStatement(q1);
            pst1.setInt(1,id);
            pst1.setString(2,medicine);
            ResultSet rs2;
            rs2=pst1.executeQuery();
            rs2.next();
            String n=rs2.getString("pname");
            String q2="select * from tbchemist where pharmacy=?";
            myconnection obj2=new myconnection();
            PreparedStatement pst2=obj2.db.prepareStatement(q2);
            pst2.setString(1,n);
            /*ResultSet rs3;
            rs3=pst2.executeQuery();
            rs3.next();
            int s=rs3.getInt("sector");*/
            String q3="select sector from tbsignup where username=?";
            String un=t2.getText();
            myconnection obj3=new myconnection();
            PreparedStatement pst3=obj3.db.prepareStatement(q3);
            pst3.setString(1,un);
            ResultSet rs3;
            rs3=pst3.executeQuery();
            rs3.next();
            int s=rs3.getInt("sector");
            String q4="select * from tbchemist where sector=? or sector=? or sector=? or sector=? or sector=?";
            myconnection obj4=new myconnection();
            PreparedStatement pst4=obj4.db.prepareStatement(q4);
            pst4.setInt(1,s-2);
            pst4.setInt(2,s-1);
            pst4.setInt(3,s);
            pst4.setInt(4,s+1);
            pst4.setInt(5,s+2);
            ResultSet rs4;
            rs3=pst4.executeQuery();
            rs3.next();
            System.out.println(rs3.getString("pharmacy"));
            l1.setText(rs3.getString("pharmacy"));
            System.out.println(rs3.getString("contact"));
            l2.setText(rs3.getString("contact"));
            rs3.next();
            System.out.println(rs3.getString("pharmacy"));
            l3.setText(rs3.getString("pharmacy"));
            System.out.println(rs3.getString("contact"));
            l4.setText(rs3.getString("contact"));
            rs3.next();
            System.out.println(rs3.getString("pharmacy"));
            l5.setText(rs3.getString("pharmacy"));
            System.out.println(rs3.getString("contact"));
            l6.setText(rs3.getString("contact"));
            rs3.next();
            System.out.println(rs3.getString("pharmacy"));
            l7.setText(rs3.getString("pharmacy"));
            System.out.println(rs3.getString("contact"));
            l8.setText(rs3.getString("contact"));
            rs3.next();
            System.out.println(rs3.getString("pharmacy"));
            l9.setText(rs3.getString("pharmacy"));
            System.out.println(rs3.getString("contact"));
            l10.setText(rs3.getString("contact"));
           
                    
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Choice c1;
    private java.awt.Choice c2;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label l1;
    private java.awt.Label l10;
    private java.awt.Label l2;
    private java.awt.Label l3;
    private java.awt.Label l4;
    private java.awt.Label l5;
    private java.awt.Label l6;
    private java.awt.Label l7;
    private java.awt.Label l8;
    private java.awt.Label l9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    // End of variables declaration//GEN-END:variables
}
